services:
  seedbox:
    build:
      context: seedbox
      dockerfile: Dockerfile
      args:
          RPC_USER: ${RPC_USER}
          RPC_PASSW: ${RPC_PASSW}
    image: ${APP_NAME}-seedbox
    container_name: ${APP_NAME}-seedbox
    env_file:
      - .env
    networks:
      - seedbox_net
    ports: 
      - ${PEER_PORT}:51413 # PEER PORT
      - ${RPC_PORT}:9091 # RPC PORT
    volumes:
      - ${MEDIA_DIR}:/media/done
      - ${TORRENT_DIR}:/torrents
    restart: always

networks:
  seedbox_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1